version: '2'
services:
    pokemon-app:
        image: pokemon
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pokemon-postgresql:5432/pokemon
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pokemon-postgresql:
        extends:
            file: postgresql.yml
            service: pokemon-postgresql
