version: '2'
services:
    pokemon-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/pokemon/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=pokemon
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
